# --- Plugins ---
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# --- Session Management ---
set-option -g destroy-unattached off 
set-option -g history-limit 25000
set -g @continuum-restore 'on'

# --- Copy and Paste ---
set-window-option -g mode-keys vi
bind i copy-mode
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy"
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "wl-copy"
bind p paste-buffer

# --- New Windows & Splits ---
bind c new-window -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"
bind M-| split-window -fh -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind M-- split-window -fv -c "#{pane_current_path}"
unbind '"'
unbind %

# --- Mouse Support ---
set -g mouse on

# --- Navigation  ---
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# --- Do not edit below this line ---
# --- Initalize TPM ---
run '~/.tmux/plugins/tpm/tpm'
