---
- name: This playbook setups the contents in /home/$USER/
  hosts: all
  pre_tasks:
    - name: Install packages
      become: yes
      ansible.builtin.dnf:
        name: 
          - neovim
          - nodejs
          - yarnpkg
        state: present

  tasks:
    - name: create ~/.bashrc.d directory
      ansible.builtin.file:
        path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.bashrc.d"
        mode: 0744
        state : directory
      tags:
        - bashrc

    - name: Setup bash configuration files.
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: 0600 
      loop:
        - src: files/home/.bashrc
          dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.bashrc"
        - src: files/home/.bashrc.d/alias.bashrc 
          dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.bashrc.d/alias.bashrc"
        - src: files/home/.bashrc.d/functions.bashrc 
          dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.bashrc.d/functions.bashrc" 
        - src: files/home/.bashrc.d/history.bashrc 
          dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.bashrc.d/history.bashrc"
        - src: files/home/.bashrc.d/ssh.bashrc 
          dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.bashrc.d/ssh.bashrc"
        - src: files/home/.bashrc.d/tmux.bashrc 
          dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.bashrc.d/tmux.bashrc"
        - src: files/home/.bashrc.d/variables.bashrc
          dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.bashrc.d/variables.bashrc"
      tags:
        - bashrc

    - name: Setup tmux configuration files.
      ansible.builtin.copy:
        src: files/home/.tmux.conf 
        dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.tmux.conf"
        mode: 0600
      tags:
         - tmux

    - name: Clone Tmux Plugin Manager repoistory. 
      ansible.builtin.git:
        repo: https://github.com/tmux-plugins/tpm 
        dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.tmux/plugins/tpm"
      tags:
        - tmux

    - name: create ~/.config/nvim directory
      ansible.builtin.file:
        path: "{{ item.path }}"
        mode: 0755
        state : directory
      loop:
        - path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.config/nvim" 
        - path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.config/nvim/site/autoload/"
      tags:
        -  nvim 

    - name: Install vim-plug for Neovim
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.config/nvim/site/autoload/"
        mode: '0644'
        force: false

    - name: Setup vim configuration files.
      ansible.builtin.copy:
        src: files/home/.config/nvim/init.vim
        dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.config/nvim/init.vim"
        mode: '0600'
      tags:
        - nvim

    - name: create ~/.local/bin directory
      ansible.builtin.file:
        path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.local/bin"
        mode: 0744
        state : directory
      tags:
        - oc

    - name: install openshift cli components
      ansible.builtin.unarchive:
        src: "{{ item.src }}" 
        dest: "{{ item.dest }}"
        mode: '0755'
        remote_src: yes
        keep_newer: yes
        list_files: yes
      loop:
        - src: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.20.14/openshift-install-linux-4.20.14.tar.gz
          dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.local/bin"
        - src: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.20.14/openshift-client-linux-4.20.14.tar.gz 
          dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.local/bin"
      tags:
        - oc
